version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=default_password
      - MYSQL_DATABASE=checkpoint
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pdefault_password"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    image: checkpoint-template
    container_name: checkpoint-template
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    ports:
      - 3000:3000

volumes:
  mysql:
    driver: local
