version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pdefault_password"]
      interval: 5s
      timeout: 5s
      retries: 20

  node:
    build: .
    command: yarn dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mysql:
    driver: local
