name: Lint and build
on: [push]
jobs:
  lint-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Set up PostgreSQL
        run: |
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE checkpoint;"
          sudo -u postgres psql -c "CREATE USER checkpoint_user WITH PASSWORD 'checkpoint_pass';"
          sudo -u postgres psql -c "ALTER DATABASE checkpoint OWNER TO checkpoint_user;"
      - run: yarn install
      - run: yarn lint
      - run: yarn build
        env:
          DATABASE_URL: 'postgresql://checkpoint_user:checkpoint_pass@localhost:5432/checkpoint'